### ISSUE TITLE
timeZone value="Japan/Tokyo" trouble

### ISSUE THREAD

**Issue by dac-liang** [WPMedia/fusion-news-theme-blocks#1002]
Hi, I am Liang.

A month ago, I changed my local blocks.json to 「Japan/Tokyo」, and it worked.

However, today, some errors appeared and caused the local PB Editor loading error.

![error log](https://user-images.githubusercontent.com/83994100/126953591-32fa7e72-1dbe-420c-ba2b-06b3a92920e7.png)

I changed it with "ja_JP" now to avoid the loading error.

Then, I confirmed the [ALC theme-settings](https://redirector.arcpublishing.com/alc/arc-products/themes/user-docs/theme-settings/) again, and searched for [tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
As the description in ALC, I think "Japan/Tokyo" should work...

Please help, thanks.

**Comment by matthewroach** [comment]
@dac-liang - Can you try setting the value as 

```"timeZone": "Asia/Tokyo"```

The timeZone value for Tokyo is `Asia/Tokyo`

**Comment by dac-liang** [comment]
Thanks a lot.

It works!!
