### ISSUE TITLE
Title typo on the README.md for video-player-block

### ISSUE THREAD

**Issue by ecarlisle** [WPMedia/fusion-news-theme-blocks#435]
The title on the `@wpmedia/video-player-block` readme says `@wpmedia/subheadline-block`.
https://github.com/WPMedia/fusion-news-theme-blocks/tree/master/blocks/video-player-block#wpmediasubheadline-block

**Comment by JackHowa** [comment]
thank you @ecarlisle -- found quite a few more typos as well ... #440
