### ISSUE TITLE
[@arc-test-org/lead-art-block] Lead art content type logic refactor

### ISSUE THREAD

**Issue by jgrosspietsch** [WPMedia/fusion-news-theme-blocks#57]
https://github.com/WPMedia/fusion-news-theme-blocks/blob/master/blocks/lead-art-block/features/leadart/default.jsx#L57

Lead art block uses logic that would be best written as a `switch` statement instead of a series of if statements. Adding new content types will only make this less readable in the future.

**Comment by JackHowa** [comment]
closing due to age
