### ISSUE TITLE
preload but not found powa drive warning

### ISSUE THREAD

**Issue by JackHowa** [WPMedia/fusion-news-theme-blocks#659]
/pf/api/v3/render/?isAdmin=true&outputType=default&_website=dagen#/:1 The resource http://d2w3jw6424abwq.cloudfront.net/prod/powaDrive.js?org=corecomponents was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

<img width="722" alt="Screen Shot 2021-01-07 at 12 47 03" src="https://user-images.githubusercontent.com/5950956/103894185-72950100-50e6-11eb-83fa-1a9f1c6453a5.png">

**Comment by matthewroach** [comment]
Fixed in https://github.com/WPMedia/fusion-news-theme-blocks/pull/772
