### ISSUE TITLE
Get promo style is duplicated in small promo manual

### ISSUE THREAD

**Issue by JackHowa** [WPMedia/fusion-news-theme-blocks#813]
------------------------------------------------------------

Match - 2 instances

./blocks/small-manual-promo-block/features/small-manual-promo/_children/promo_style.jsx:1,28
function getPromoStyle(position = 'right', element = 'container') {
  const imagePositionClassMapping = {
    right: {
      container: 'row',
      margin: 'image-right',
      headlineMargin: 'margin-md-right',
    },
    left: {
      container: 'row',
      margin: 'image-left',
      headlineMargin: 'margin-md-left',
    },
    above: {
      container: '',
      margin: ' image-above',
      headlineMargin: 'margin-md-top',
    },
    below: {
      container: '',
      margin: 'margin-sm-bottom image-below',
      headlineMargin: 'margin-md-bottom',
    },
  };
  const promoClasses = imagePositionClassMapping[position][element];
  return promoClasses;
}
export default getPromoStyle;

./blocks/small-promo-block/features/small-promo/_children/promo_style.jsx:1,28
function getPromoStyle(position = 'right', element = 'container') {
  const imagePositionClassMapping = {
    right: {
      container: 'row',
      margin: 'image-right',
      headlineMargin: 'margin-md-right',
    },
    left: {
      container: 'row',
      margin: 'image-left',
      headlineMargin: 'margin-md-left',
    },
    above: {
      container: '',
      margin: ' image-above',
      headlineMargin: 'margin-md-top',
    },
    below: {
      container: '',
      margin: 'margin-sm-bottom image-below',
      headlineMargin: 'margin-md-bottom',
    },
  };
  const promoClasses = imagePositionClassMapping[position][element];
  return promoClasses;
}
export default getPromoStyle;

**Comment by matthewroach** [comment]
Fixed with https://github.com/WPMedia/fusion-news-theme-blocks/pull/816
