### ISSUE TITLE
How to implement navigation chain for multi sites.

### ISSUE THREAD

**Issue by dac-liang** [WPMedia/fusion-news-theme-blocks#865]
Hi, I am Liang from DAC (Japan).

Currently, I am learning about how to use theme blocks.
I am wondering how to implement navigation chain for multi sites.

It seems no way to append 「?_website=${arcSite}」to link with node_type="section".

https://github.com/WPMedia/fusion-news-theme-blocks/blob/stable/blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/section-nav.jsx#L10

Thanks for reading, hope someone can help.

**Comment by matthewroach** [comment]
I am going to assume you are working locally with Fusion and the theme blocks. As working locally requires the use the of the `_website` query string parameter. As this isn't required on production (CDN) URL's it is not something that is accounted for when running within an environment where it is required. You would need to manually add the query string after navigating to a page. Or you could inject some script to do it for you

**Comment by dac-liang** [comment]
Thanks for your reply!

Our team didn't know about the practice of using CDN.
Nice to know it today~

I searched in arc answers and found some info from [answers/1533/]. 

Since we are reseller, not really publishing sites currently, mainly developing on localhost.
It seems "inject some script" would be better for us.

Really helpful.
